const throwError = (error, message) => {
    throw new error(message);
};

export default throwError;